/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koneksi_java;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class beliBuku extends javax.swing.JFrame {
private DefaultTableModel model,model2;
    /**
     * Creates new form beliBuku
     */
    public beliBuku() {
        initComponents();
        pilihLB.setVisible(false);
        pilihCMB.setVisible(false);
        bayarBT.setVisible(false);
        simpanBT.setVisible(false);
        model=new DefaultTableModel();
        model2=new DefaultTableModel();
        keranjangTB.setModel(model);
        model.addColumn("Id_Buku");
        model.addColumn("Nama_Buku");
        model.addColumn("Jumlah_Beli");
        model.addColumn("Total_Harga");
        idbukuTB.setModel(model2);
        model2.addColumn("Id_Buku");
        model2.addColumn("Nama_Buku");
        getData();
        getData2();
        hapusTF.setEditable(false);
        bukuTF.setEditable(false);
        jumlahTF.setEditable(false);
        totalTF.setEditable(false);
        pesananLB.setVisible(false);
        transaksiLB.setVisible(false);
        pesananTF.setVisible(false);
        stokTF.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**public void noPesanan1(){
        try {
            Connection koneksikan=koneksi.getkoneksikan();
            String sql="select max(id_transaksi) from transaksi";
            Statement st=koneksikan.createStatement();
            ResultSet r=st.executeQuery(sql);
            while(r.next()){
                Object[] obj=new Object[1];
                obj[0]=r.getString("id_transaksi");
                if(obj[0]==null){
                    obj[0]="BR000";
                    pesananTF.setText("BR000");
                }
                String kode=(String) obj[0];
                String kd=kode.substring(1,5);
                int nomor=Integer.parseInt(kd);
                nomor++;
                String a=String.format("%3d", nomor);
                String b="BR"+a;
                pesananTF.setText(b);
            }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
    }**/
    /**public void noPesanan(){
            try {
            Connection koneksikan=koneksi.getkoneksikan();
            String sql="select *from transaksi order by id_transaksi desc";
            Statement st=koneksikan.createStatement();
            ResultSet r=st.executeQuery(sql);
            if(r.next()){
                   String noPesanan=r.getString("id_transaksi").substring(1);
                   String AN=""+(Integer.parseInt(pesananTF.getText())+1);
                   String Nol="";
                   if(AN.length()==1){Nol="000";}
                   else if(AN.length()==2){Nol="00";}
                   else if(AN.length()==3){Nol="0";}
                   else if(AN.length()==4){Nol="";}
                   pesananTF.setText("B"+Nol+AN);
                }else{
                pesananTF.setText("B0001");
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }**/
    public void noPesanan(){
            try {
            Connection koneksikan=koneksi.getkoneksikan();
            String sql="select max(right(id_transaksi,6)) from transaksi";
            Statement st=koneksikan.createStatement();
            ResultSet r=st.executeQuery(sql);
            while(r.next()){
                if (r.first()==false){
                    pesananTF.setText("TR-000001");
                }else{
                    r.last();
                    int nomor=r.getInt(1)+1;
                    String no=String.valueOf(nomor);
                    int nomorTransaksi=no.length();
                    for(int i=0;i<6-nomorTransaksi;i++){
                    no="0"+no;
                }
                    pesananTF.setText("TR-"+no);
                }
            }
            r.close();
            st.close();
            }
            
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }
    public void hapus(){
        hapusTF.setText("");
        bukuTF.setText("");
        jumlahTF.setText("");
        totalTF.setText("");
        alamatTF.setText("");
        namaTF.setText("");
        nomorTF.setText("");
        stokTF.setText("");
        pesananTF.setText("");
    }
    public void stok(){
        try {
            Connection koneksikan=koneksi.getkoneksikan();
            Statement s=koneksikan.createStatement();
            String sql="select jumlah_stok from data_buku where id_buku='"+hapusTF.getText()+"'";
            ResultSet r=s.executeQuery(sql);
            while(r.next()){
                   String stok1=r.getString("jumlah_stok");
                   stokTF.setText(stok1);
                }   
        } catch (Exception e) {
        }
    }
    public void getData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection koneksikan=koneksi.getkoneksikan();
            Statement s=koneksikan.createStatement();
            String sql="SELECT *from keranjang1";
                ResultSet r=s.executeQuery(sql);
                while(r.next()){
                    Object[] obj = new Object[4];
                    obj[0]=r.getString("id_buku");
                    obj[1]=r.getString("nama_buku");
                    obj[2]=r.getString("jumlah_beli");
                    obj[3]=r.getString("total");
                    model.addRow(obj);
                }
                r.close();
                s.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void getData2(){
        model2.getDataVector().removeAllElements();
        model2.fireTableDataChanged();
        try {
            Connection koneksikan=koneksi.getkoneksikan();
            Statement s=koneksikan.createStatement();
            String sql="select id_buku, nama_buku from keranjang";
                ResultSet r=s.executeQuery(sql);
                while(r.next()){
                    Object[] obj = new Object[2];
                    obj[0]=r.getString("id_buku");
                    obj[1]=r.getString("nama_buku");
                    model2.addRow(obj);
                }
                r.close();
                s.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keranjangTB = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pilihLB = new javax.swing.JLabel();
        pesananLB = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        alamatTF = new javax.swing.JTextField();
        nomorTF = new javax.swing.JTextField();
        lanjutBT = new javax.swing.JButton();
        pilihCMB = new javax.swing.JComboBox<>();
        bayarBT = new javax.swing.JButton();
        hapusBT = new javax.swing.JButton();
        hapusTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bukuTF = new javax.swing.JTextField();
        jumlahTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        idbukuTB = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        terimaTF = new javax.swing.JTextField();
        diterimaBT = new javax.swing.JButton();
        simpanBT = new javax.swing.JButton();
        stokTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        transaksiLB = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pesananTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(680, 440));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selamat berbelanja");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 68, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Keranjang");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2leftarrow.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        keranjangTB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        keranjangTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Buku", "Nama Buku", "Jumlah Beli", "Total Harga"
            }
        ));
        keranjangTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keranjangTB.setGridColor(new java.awt.Color(255, 153, 102));
        keranjangTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keranjangTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(keranjangTB);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 540, 215);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Belum bayar");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 0, 80, 20);

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 560, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pembayaran");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        pilihLB.setForeground(new java.awt.Color(255, 255, 255));
        pilihLB.setText("Metode pembayaran:");
        jPanel3.add(pilihLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 120, 20));

        pesananLB.setForeground(new java.awt.Color(255, 255, 255));
        pesananLB.setText("Nomor Pesanan:");
        jPanel3.add(pesananLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 110, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 90, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nomor telepon:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 100, 20));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        jPanel3.add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 180, -1));
        jPanel3.add(alamatTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 180, -1));
        jPanel3.add(nomorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 180, -1));

        lanjutBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2rightarrow.png"))); // NOI18N
        lanjutBT.setText("Lanjut");
        lanjutBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lanjutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutBTActionPerformed(evt);
            }
        });
        jPanel3.add(lanjutBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, -1, -1));

        pilihCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "Alfamart", "Indomart" }));
        pilihCMB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(pilihCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 160, -1));

        bayarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bantuan.png"))); // NOI18N
        bayarBT.setText("Bayar");
        bayarBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bayarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBTActionPerformed(evt);
            }
        });
        jPanel3.add(bayarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, -1, 30));

        hapusBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cancel-2-16x16.png"))); // NOI18N
        hapusBT.setText("Hapus");
        hapusBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBTActionPerformed(evt);
            }
        });
        jPanel3.add(hapusBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, -1));
        jPanel3.add(hapusTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 160, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total harga:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id buku:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama buku:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jumlah beli:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        bukuTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuTFActionPerformed(evt);
            }
        });
        jPanel3.add(bukuTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 160, -1));
        jPanel3.add(jumlahTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 160, -1));
        jPanel3.add(totalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 160, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        idbukuTB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idbukuTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Buku", "Nama Buku"
            }
        ));
        idbukuTB.setToolTipText("");
        idbukuTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idbukuTB.setGridColor(new java.awt.Color(255, 153, 102));
        idbukuTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idbukuTBMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(idbukuTB);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 270, 120);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sudah bayar");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 0, 90, 20);
        jPanel2.add(terimaTF);
        terimaTF.setBounds(10, 150, 160, 30);

        diterimaBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Checkbox.png"))); // NOI18N
        diterimaBT.setText("Diterima");
        diterimaBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diterimaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diterimaBTActionPerformed(evt);
            }
        });
        jPanel2.add(diterimaBT);
        diterimaBT.setBounds(180, 150, 100, 30);

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 290, 190));

        simpanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/accept.png"))); // NOI18N
        simpanBT.setText("Simpan");
        simpanBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBTActionPerformed(evt);
            }
        });
        jPanel3.add(simpanBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));
        jPanel3.add(stokTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 160, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Stok:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, 20));

        transaksiLB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        transaksiLB.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLB.setText("Transaksi");
        jPanel3.add(transaksiLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nama pembeli:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 100, 20));
        jPanel3.add(pesananTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 170, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/upnarrow2.png"))); // NOI18N
        jButton1.setText("Refresh");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        home hm=new home();
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void lanjutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutBTActionPerformed
        // TODO add your handling code here:
        String nama=namaTF.getText();
        String alamat=alamatTF.getText();
        String nomor=nomorTF.getText();
        if(namaTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nama pembeli tidak boleh kosong");
            namaTF.requestFocus();
        }
        else if(alamatTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Alamat pembeli tidak boleh kosong");
            alamatTF.requestFocus();
        }
        else if(nomorTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nomor telepon pembeli tidak boleh kosong");
            nomorTF.requestFocus();
        }
        else{
            JOptionPane.showMessageDialog(null, nama+", "+alamat+", "+nomor);
            int reply=JOptionPane.showConfirmDialog(
            null,"Yakin simpan data pembeli","Data pembeli",JOptionPane.YES_NO_OPTION);
            if(reply==JOptionPane.YES_OPTION){
                namaTF.setEditable(false);
                alamatTF.setEditable(false);
                nomorTF.setEditable(false);
                pilihLB.setVisible(true);
                pilihCMB.setVisible(true);
                simpanBT.setVisible(true);
            } 
        }
    }//GEN-LAST:event_lanjutBTActionPerformed

    private void keranjangTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keranjangTBMouseClicked
        // TODO add your handling code here:
        hapusTF.setText(keranjangTB.getValueAt(keranjangTB.getSelectedRow(),0).toString());
        bukuTF.setText(keranjangTB.getValueAt(keranjangTB.getSelectedRow(),1).toString());
        jumlahTF.setText(keranjangTB.getValueAt(keranjangTB.getSelectedRow(),2).toString());
        totalTF.setText(keranjangTB.getValueAt(keranjangTB.getSelectedRow(),3).toString());
        stok();
    }//GEN-LAST:event_keranjangTBMouseClicked

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
        // TODO add your handling code here:
        int reply=JOptionPane.showConfirmDialog(
                null,"Anda akan menghapus data ini","Hapus",JOptionPane.YES_NO_OPTION);
        if(reply==JOptionPane.YES_OPTION){
            try {
                String id=hapusTF.getText();
                Connection koneksikan=koneksi.getkoneksikan();
                Statement s=koneksikan.createStatement();
                        System.out.println("Database ditemukan");                   
                        String input="delete from keranjang1 where id_buku= '"+id+"'";
                        s.executeUpdate(input); 
                        String pesan="Berhasil menghapus buku";
                        JOptionPane.showMessageDialog(null, pesan,"Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                        hapusTF.setText("");
                        bukuTF.setText("");
                        jumlahTF.setText("");
                        totalTF.setText("");
               } catch (SQLException ex) {
                   System.err.println("SQLException: "+ex.getMessage());
               }
        }
        
    }//GEN-LAST:event_hapusBTActionPerformed

    private void bukuTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bukuTFActionPerformed

    private void bayarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBTActionPerformed
        // TODO add your handling code here:
            Connection koneksikan=koneksi.getkoneksikan();
            String transaksi=pesananTF.getText();
            String id=hapusTF.getText();
            String nama=bukuTF.getText();
            String jumlah=jumlahTF.getText();
            String total=totalTF.getText();
            String metode=(String) pilihCMB.getSelectedItem();
            String pembeli=namaTF.getText();
            String alamat=alamatTF.getText();
            String nomor=nomorTF.getText();
            int a1,a2,a3;
             a1 = Integer.parseInt(jumlah);
             a2 = Integer.parseInt(total);
             a3=a2/a1;
        try {
            Statement s=koneksikan.createStatement();
            String input="insert into transaksi values('"+transaksi+"','"+id+"',"+"'"+nama+"',"+"'"+pembeli+"','"+alamat+"','"+nomor+"','"+metode+"','"+jumlah+"','"+a3+"','"+total+"')";
            s.executeUpdate(input); 
            JOptionPane.showMessageDialog(null, transaksi+", "+metode);
            String pesan="Berhasil membayar buku";
            JOptionPane.showMessageDialog(null, pesan,"Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            jPanel2.setVisible(true);
            hapus();
        } catch (SQLException ex) {
            System.err.println("SQLException: "+ex.getMessage());
        }
    }//GEN-LAST:event_bayarBTActionPerformed

    private void idbukuTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idbukuTBMouseClicked
        // TODO add your handling code here:
        terimaTF.setText(idbukuTB.getValueAt(idbukuTB.getSelectedRow(),0).toString());
    }//GEN-LAST:event_idbukuTBMouseClicked

    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed
        // TODO add your handling code here:
            String id=hapusTF.getText();
            String nama=bukuTF.getText();
            String jumlah=jumlahTF.getText();
            String total=totalTF.getText();
            String metode=(String) pilihCMB.getSelectedItem();
            String pembeli=namaTF.getText();
            String alamat=alamatTF.getText();
            String nomor=nomorTF.getText();
            String stok=stokTF.getText();
             int a1,a2,a3;
             a1 = Integer.parseInt(jumlah);
             a2 = Integer.parseInt(stok);
             a3=a2-a1;
             if(metode.equals("--pilih--")){
                 JOptionPane.showMessageDialog(rootPane, "Anda belum memasukkan jumlah beli");
             }
             else{
            try {
                Connection koneksikan=koneksi.getkoneksikan();
                Statement s=koneksikan.createStatement();
                String input="insert into keranjang values('"+id+"',"+"'"+nama+"',"+"'"+jumlah+"',"+"'"+total+"',"+"'"+metode+"',"+"'"+pembeli+"',"+"'"+alamat+"',"+"'"+nomor+"',"+"'"+a3+"')";
                s.executeUpdate(input); 
                String pesan="Berhasil menyimpan buku, untuk selanjutnya Anda bisa klik bayar";
                JOptionPane.showMessageDialog(null, pesan,"Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                bayarBT.setVisible(true);
                pesananLB.setVisible(true);
                transaksiLB.setVisible(true);
                pesananTF.setVisible(true);
                pesananTF.setEditable(false);
            try {
                 System.out.println("Database ditemukan");                   
                 String hapus="delete from keranjang1 where id_buku= '"+id+"'";
                 s.executeUpdate(hapus); 
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
             try {
                 System.out.println("Database ditemukan");                   
                 String update="update data_buku set jumlah_stok='"+a3+"'where id_buku='"+id+"'";
                 s.executeUpdate(update); 
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                } catch (SQLException ex) {
                    System.err.println("SQLException: "+ex.getMessage());
                }}
             noPesanan();          
    }//GEN-LAST:event_simpanBTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getData();
        getData2();
        hapus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void diterimaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diterimaBTActionPerformed
        // TODO add your handling code here:
         int reply=JOptionPane.showConfirmDialog(
                null,"Pesanan diterima?","Konfirmasi Pesanan",JOptionPane.YES_NO_OPTION );
         if(terimaTF.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Pilih ID Buku terlebih dahulu","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
         }
         else{
             if(reply==JOptionPane.YES_OPTION){
            try {
            String id=terimaTF.getText();
            Connection koneksikan=koneksi.getkoneksikan();
            Statement s=koneksikan.createStatement();
            System.out.println("Database ditemukan");                   
            String hapus="delete from keranjang where id_buku= '"+id+"'";
            s.executeUpdate(hapus);  
            terimaTF.setText("");
            String pesan="Berhasil konfirmasi buku";
            JOptionPane.showMessageDialog(null, pesan,"Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            }
        }else{
            beliBuku b=new beliBuku();
            b.setVisible(true);
            dispose();
        }
        }
    }//GEN-LAST:event_diterimaBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beliBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beliBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beliBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beliBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beliBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTF;
    private javax.swing.JButton bayarBT;
    private javax.swing.JTextField bukuTF;
    private javax.swing.JButton diterimaBT;
    private javax.swing.JButton hapusBT;
    private javax.swing.JTextField hapusTF;
    private javax.swing.JTable idbukuTB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlahTF;
    private javax.swing.JTable keranjangTB;
    private javax.swing.JButton lanjutBT;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField nomorTF;
    private javax.swing.JLabel pesananLB;
    private javax.swing.JTextField pesananTF;
    private javax.swing.JComboBox<String> pilihCMB;
    private javax.swing.JLabel pilihLB;
    private javax.swing.JButton simpanBT;
    private javax.swing.JTextField stokTF;
    private javax.swing.JTextField terimaTF;
    private javax.swing.JTextField totalTF;
    private javax.swing.JLabel transaksiLB;
    // End of variables declaration//GEN-END:variables
}
