/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koneksi_java;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class daftar extends javax.swing.JFrame {

    /**
     * Creates new form daftar
     */
    public daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**public void kosong(){
        idTF.setText("");
        UsernameTF.setText("");
        EmailTF.setText("");
        PasswordTF.setText("");
        Password2TF.setText("");
        idTF.requestFocus();
    }**/
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        Password2TF = new javax.swing.JPasswordField();
        RegisterBT = new javax.swing.JButton();
        errorLB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(240, 223, 154));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 460));
        jPanel2.setPreferredSize(new java.awt.Dimension(680, 440));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 104, 20));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 104, 20));

        EmailTF.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jPanel2.add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 158, -1));

        PasswordTF.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel2.add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 158, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Repeat Password:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        Password2TF.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel2.add(Password2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 158, -1));

        RegisterBT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RegisterBT.setText("Register");
        RegisterBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBT.setPreferredSize(new java.awt.Dimension(77, 25));
        RegisterBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBTActionPerformed(evt);
            }
        });
        jPanel2.add(RegisterBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 91, 30));

        errorLB.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(errorLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 266, 18));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2leftarrow.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Username:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 104, 22));

        UsernameTF.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jPanel2.add(UsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 158, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Daftar");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please insert your data");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Berdikari-Book");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Version 1.0");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("F:\\PICTURE\\Picture\\2041-3.jpg")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-680, -320, 1480, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBTActionPerformed
        // TODO add your handling code here:
           // String id=idTF.getText();
            String username=UsernameTF.getText();
            String email=EmailTF.getText();
            String password=PasswordTF.getText();
            String cek=null;
            Connection koneksikan=koneksi.getkoneksikan();
            try {
                Statement s=koneksikan.createStatement();
                String sql="SELECT * FROM user WHERE username= '"+username+"'";
                ResultSet r=s.executeQuery(sql);
                while(r.next()){
                    cek=r.getString("username");;
                }
                r.close();
                s.close();
            } catch (Exception e) {
                System.out.println("Maaf terjadi kesalahan");
            }
            if(cek!=null) {
                String daf="Username yang anda masukkan sudah terdaftar";
                JOptionPane.showMessageDialog(null, daf,"Pesan kesalahan",JOptionPane.INFORMATION_MESSAGE);
            }
            if(!PasswordTF.getText().equals(Password2TF.getText())){
                errorLB.setText("Password yang Anda ketikkan tidak cocok");
            }
            else{
                try {
                    if (UsernameTF.getText().equals("")){
                        JOptionPane.showMessageDialog(rootPane, "User Name tidak boleh kosong");
                        UsernameTF.requestFocus();
                    }
                    else if (EmailTF.getText().equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Email tidak boleh kosong");
                        EmailTF.requestFocus();
                     }
                    else if (PasswordTF.getText().equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Password tidak boleh kosong");
                        PasswordTF.requestFocus();
                     }
                    else{
                        Statement s=koneksikan.createStatement();
                        System.out.println("Database ditemukan");                   
                        String input="insert into user values('"+username+"',"+"'"+email+"',"+"'"+password+"')";
                        s.executeUpdate(input);                   
                        /**String query="INSERT INTO user(username,email,password)VALUES(?,md5(?))";
                        PreparedStatement p=koneksikan.prepareStatement(query);
                        p.setString(1, username);
                        p.setString(2, email);
                        p.setString(3, password);
                        p.executeUpdate();
                        p.close();**/
                        String pesan="Anda berhasil mendaftar";
                        JOptionPane.showMessageDialog(null, pesan,"Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                        login2 lg=new login2();
                        lg.setVisible(true);  
                }}catch (SQLException ex) {
                    System.err.println("SQLException: "+ex.getMessage());
                    }
            }
    }//GEN-LAST:event_RegisterBTActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        login lg=new login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTF;
    private javax.swing.JPasswordField Password2TF;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JButton RegisterBT;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel errorLB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
