/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package koneksi_java;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class home extends javax.swing.JFrame {
private DefaultTableModel model;
    /** Creates new form home */
    public home() {
        initComponents();
        namaLB.setText(login2.user1);
        model=new DefaultTableModel();
        bukuTB.setModel(model);
        model.addColumn("Id_Buku");
        model.addColumn("Nama_Buku");
        model.addColumn("Nama_Pengarang");
        model.addColumn("Nama_Penerbit");
        model.addColumn("Jumlah_Halaman");
        model.addColumn("Tahun_Penerbit");
        model.addColumn("Jumlah_Stok");
        model.addColumn("Harga");
        getData();
        jPanel5.setVisible(false);
        idTF.setEditable(false);
        namaTF.setEditable(false);
        namapengarangTF.setEditable(false);
        namapenerbitTF.setEditable(false);
        jumlahhalamanTF.setEditable(false);
        tahunTF.setEditable(false);
        jumlahstokTF.setEditable(false);
        hargaTF.setEditable(false);
    }
    public void getData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection koneksikan=koneksi.getkoneksikan();
            Statement s=koneksikan.createStatement();
            String sql="SELECT *from data_buku";
                ResultSet r=s.executeQuery(sql);
                while(r.next()){
                    Object[] obj = new Object[8];
                    obj[0]=r.getString("id_buku");
                    obj[1]=r.getString("nama_buku");
                    obj[2]=r.getString("nama_pengarang");
                    obj[3]=r.getString("nama_penerbit");
                    obj[4]=r.getString("jml_halaman");
                    obj[5]=r.getString("tahun_terbit");
                    obj[6]=r.getString("jumlah_stok");
                    obj[7]=r.getString("harga");
                    model.addRow(obj);
                }
                r.close();
                s.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        namaLB = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cariTF = new javax.swing.JTextField();
        cariLB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bukuTB = new javax.swing.JTable();
        profilLB = new javax.swing.JLabel();
        keranjangLB = new javax.swing.JLabel();
        pilihBT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kembaliLB = new javax.swing.JLabel();
        beliBT = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        namapengarangTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        namapenerbitTF = new javax.swing.JTextField();
        tahunTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jumlahhalamanTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jumlahstokTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        hargaTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        beliTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 460));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat Datang,");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        namaLB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        namaLB.setForeground(new java.awt.Color(255, 255, 255));
        namaLB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(namaLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 152, 30));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cariTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(cariTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 440, -1));

        cariLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari hijau.png"))); // NOI18N
        cariLB.setToolTipText("Cari");
        cariLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cariLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariLBMouseClicked(evt);
            }
        });
        jPanel3.add(cariLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, 40));

        bukuTB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bukuTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Buku", "Nama Buku", "Nama Pengarang", "Nama Penerbit", "Jumlah Halaman", "Tahun Terbit", "Jumlah Stok", "Harga"
            }
        ));
        bukuTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bukuTB.setGridColor(new java.awt.Color(255, 153, 102));
        bukuTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bukuTB);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 560, 282));

        profilLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/setupuser.png"))); // NOI18N
        profilLB.setToolTipText("Profil");
        profilLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profilLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilLBMouseClicked(evt);
            }
        });
        jPanel3.add(profilLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        keranjangLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/CategoryProducts.png"))); // NOI18N
        keranjangLB.setToolTipText("Keranjang");
        keranjangLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keranjangLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keranjangLBMouseClicked(evt);
            }
        });
        jPanel3.add(keranjangLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 20, 20));

        pilihBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2rightarrow.png"))); // NOI18N
        pilihBT.setText("Pilih Buku");
        pilihBT.setToolTipText("");
        pilihBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilihBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihBTActionPerformed(evt);
            }
        });
        jPanel3.add(pilihBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, 580, 380));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Berdikari-Book");
        jLabel9.setToolTipText("");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id buku:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, -1));

        idTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Detail buku");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 373, -1, 16));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pilih Buku");
        jLabel8.setToolTipText("");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 24, -1, -1));

        kembaliLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2leftarrow.png"))); // NOI18N
        kembaliLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembaliLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliLBMouseClicked(evt);
            }
        });
        jPanel5.add(kembaliLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        beliBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        beliBT.setText("Tambah keranjang");
        beliBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beliBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBTActionPerformed(evt);
            }
        });
        jPanel5.add(beliBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama buku:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel5.add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama pengarang:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel5.add(namapengarangTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama penerbit:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel5.add(namapenerbitTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 180, -1));
        jPanel5.add(tahunTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 181, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jumlah halaman:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel5.add(jumlahhalamanTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 181, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tahun terbit:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel5.add(jumlahstokTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 181, -1));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Jumlah stok:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        jPanel5.add(hargaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 181, -1));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Harga:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jumlah beli:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Masukkan jumlah beli untuk membeli buku");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        beliTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliTFActionPerformed(evt);
            }
        });
        jPanel5.add(beliTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 183, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 340, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void pilihBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBTActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        jPanel5.setVisible(true);
    }//GEN-LAST:event_pilihBTActionPerformed

    private void keranjangLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keranjangLBMouseClicked
        // TODO add your handling code here:
        beliBuku bl=new beliBuku();
        bl.setVisible(true);
        dispose();
    }//GEN-LAST:event_keranjangLBMouseClicked

    private void profilLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilLBMouseClicked
        // TODO add your handling code here:
        profil p=new profil();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_profilLBMouseClicked

    private void bukuTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuTBMouseClicked
        // TODO add your handling code here:
        idTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),0).toString());
        namaTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),1).toString());
        namapengarangTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),2).toString());
        namapenerbitTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),3).toString());
        jumlahhalamanTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),4).toString());
        tahunTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),5).toString());
        jumlahstokTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),6).toString());
        hargaTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),7).toString());
    }//GEN-LAST:event_bukuTBMouseClicked

    private void cariLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariLBMouseClicked
        // TODO add your handling code here:\
        String cari=cariTF.getText();
        Connection koneksikan=koneksi.getkoneksikan();
        if (cari.equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Masukkan keyword buku terlebih dahulu");
                        cariTF.requestFocus();
                        getData();
                    }
        else{
        try {
            int baris=model.getRowCount();
            for(int i=1;i<=baris;i++){
                model.removeRow(0);
            }
            Statement s=koneksikan.createStatement();
            String sql="SELECT *from data_buku where nama_buku like'%"+cari+"%'or id_buku like '%"+cari+"%'";
            ResultSet r=s.executeQuery(sql);
            while(r.next()){
                model.addRow(new String[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                });
            }
            bukuTB.setModel(model);
            cariTF.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Buku yang Anda cari tidak tersedia");
            System.err.println("error(search):"+ex);
        }}

    }//GEN-LAST:event_cariLBMouseClicked

    private void beliTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beliTFActionPerformed

    private void beliBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBTActionPerformed
        // TODO add your handling code here:
        if (beliTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Anda belum memasukkan jumlah beli");
            beliTF.requestFocus();
        }
        else{
            try {
                Connection koneksikan=koneksi.getkoneksikan();
                Statement s=koneksikan.createStatement();
                String id=idTF.getText();
                String nama=namaTF.getText();
                String jumlah=beliTF.getText();
                String harga=hargaTF.getText();
                int a1,total,a2;
                a1 = Integer.parseInt(harga);
                a2 = Integer.parseInt(jumlah);
                total=a1*a2;
                String input="insert into keranjang1 values('"+id+"',"+"'"+nama+"',"+"'"+jumlah+"',"+"'"+total+"')";
                s.executeUpdate(input); 
                String pesan="Berhasil menambahkan buku di keranjang";
                JOptionPane.showMessageDialog(null, pesan,"Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                beliBuku bl=new beliBuku();
                bl.setVisible(true);
                dispose();
            } catch (SQLException ex) {
                    System.err.println("SQLException: "+ex.getMessage());
        }
        }
    }//GEN-LAST:event_beliBTActionPerformed

    private void kembaliLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliLBMouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_kembaliLBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beliBT;
    private javax.swing.JTextField beliTF;
    private javax.swing.JTable bukuTB;
    private javax.swing.JLabel cariLB;
    private javax.swing.JTextField cariTF;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahhalamanTF;
    private javax.swing.JTextField jumlahstokTF;
    private javax.swing.JLabel kembaliLB;
    private javax.swing.JLabel keranjangLB;
    private javax.swing.JLabel namaLB;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField namapenerbitTF;
    private javax.swing.JTextField namapengarangTF;
    private javax.swing.JButton pilihBT;
    private javax.swing.JLabel profilLB;
    private javax.swing.JTextField tahunTF;
    // End of variables declaration//GEN-END:variables

}
