/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koneksi_java;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class laporanPenjualan extends javax.swing.JFrame {
private DefaultTableModel model;
    /**
     * Creates new form laporanPenjualan
     */
    public laporanPenjualan() {
        initComponents();
        Tanggal_sekarang();
        Jam_digital();
        model=new DefaultTableModel();
        bukuTB.setModel(model);
        model.addColumn("Id_Jual");
        model.addColumn("Id_Buku");
        model.addColumn("Nama_Buku");
        model.addColumn("Harga_Buku");
        model.addColumn("Nama_Pembeli");
        model.addColumn("Jumlah_Buku");
        model.addColumn("Total_Harga");
        idTF.setEditable(false);
        idbukuTF.setEditable(false);
        hargaTF.setEditable(false);
        jumlahTF.setEditable(false);
        keseluruhanTF.setEditable(false);
        labaTF.setEditable(false);
        namaTF.setEditable(false);
        pembeliTF.setEditable(false);
        totalTF.setEditable(false); 
        getData();
        labakotor();
        totalkeseluruhan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void labakotor(){
        try {
            Connection koneksikan=koneksi.getkoneksikan();
            Statement s=koneksikan.createStatement();
            String sql1="select SUM(total_harga)from data_penjualan_buku";
                ResultSet r=s.executeQuery(sql1);
                while(r.next()){
                    String total=r.getString("sum(total_harga)");
                    labaTF.setText("Rp. "+total);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void totalkeseluruhan(){
        try {
            Connection koneksikan=koneksi.getkoneksikan();
            Statement s=koneksikan.createStatement();
            String sql2="select SUM(jumlah_buku) from data_penjualan_buku";
                ResultSet r=s.executeQuery(sql2);
                while(r.next()){
                    String total=r.getString("sum(jumlah_buku)");
                    keseluruhanTF.setText(total);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void getData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection koneksikan=koneksi.getkoneksikan();
            Statement s=koneksikan.createStatement();
            String sql="SELECT *from data_penjualan_buku";
                ResultSet r=s.executeQuery(sql);
                while(r.next()){
                    Object[] obj = new Object[7];
                    obj[0]=r.getString("id_jual");
                    obj[1]=r.getString("id_buku");
                    obj[2]=r.getString("nama_buku");
                    obj[3]=r.getString("harga_buku");
                    obj[4]=r.getString("nama_pembeli");
                    obj[5]=r.getString("jumlah_buku");
                    obj[6]=r.getString("total_harga");
                    model.addRow(obj);
                }
                r.close();
                s.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void Tanggal_sekarang(){
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("yyyy-MM-dd") ;
        tanggalLB.setText(kal.format(sekarang));
    }
    
    //penrintah menampilkan jam
    public void Jam_digital(){
        new Thread(){
            @Override
            public void run(){
                int waktu_mulai = 0;
                while (waktu_mulai == 0){
                Calendar kalender = new GregorianCalendar();
                int jam = kalender.get(Calendar.HOUR);
                int menit = kalender.get(Calendar.MINUTE);
                int detik = kalender.get(Calendar.SECOND);
                int AM_PM = kalender.get(Calendar.AM_PM);
                String siang_malam = "";
                if (AM_PM == 1){
                    siang_malam = "PM";
                }
                else {
                    siang_malam = "AM";
                }
                String time = jam+" : "+menit+" : "+detik+" "+siang_malam;
                jamLB.setText(time);
                }
            }
        }.start();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jamLB = new javax.swing.JLabel();
        tanggalLB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bukuTB = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        idbukuTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hargaTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pembeliTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jumlahTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();
        refreshBT = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        keseluruhanTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        labaTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(null);

        jamLB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jamLB.setForeground(new java.awt.Color(255, 255, 255));
        jamLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jamLB.setText("JAM");
        jPanel3.add(jamLB);
        jamLB.setBounds(540, 20, 150, 40);

        tanggalLB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggalLB.setForeground(new java.awt.Color(255, 255, 255));
        tanggalLB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggalLB.setText("TANGGAL");
        jPanel3.add(tanggalLB);
        tanggalLB.setBounds(10, 20, 230, 40);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Laporan Penjualan");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        bukuTB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bukuTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Jual", "Id Buku", "Nama Buku", "Harga Buku", "Nama Pembeli", "Jumlah Buku", "Total Harga"
            }
        ));
        bukuTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bukuTB.setGridColor(new java.awt.Color(255, 153, 102));
        bukuTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bukuTB);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 690, 190));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id jual:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 20));

        idTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Id buku:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 20));
        jPanel2.add(idbukuTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama buku:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 20));
        jPanel2.add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 200, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Harga buku");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 20));
        jPanel2.add(hargaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama pembeli:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 130, 20));
        jPanel2.add(pembeliTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 190, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Jumlah buku:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, 20));
        jPanel2.add(jumlahTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 190, -1));
        jPanel2.add(totalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 190, -1));

        refreshBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh kecil.png"))); // NOI18N
        refreshBT.setText("Refresh");
        refreshBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTActionPerformed(evt);
            }
        });
        jPanel2.add(refreshBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save-16x16.png"))); // NOI18N
        jButton4.setText("Simpan");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total harga:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 70, -1));
        jPanel2.add(keseluruhanTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, -1));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total keseluruhan buku yang dijual dan laba:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 270, -1));
        jPanel2.add(labaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 130, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b_print.png"))); // NOI18N
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bukuTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuTBMouseClicked
        // TODO add your handling code here:
        idTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),0).toString());
        idbukuTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),1).toString());
        namaTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),2).toString());
        hargaTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),3).toString());
        pembeliTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),4).toString());
        jumlahTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),5).toString());
        totalTF.setText(bukuTB.getValueAt(bukuTB.getSelectedRow(),6).toString());
    }//GEN-LAST:event_bukuTBMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        homeAdmin hm=new homeAdmin();
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void refreshBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTActionPerformed
        // TODO add your handling code here:
        totalkeseluruhan();
        labakotor();
    }//GEN-LAST:event_refreshBTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Data berhasil dicetak!!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bukuTB;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JTextField idbukuTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jamLB;
    private javax.swing.JTextField jumlahTF;
    private javax.swing.JTextField keseluruhanTF;
    private javax.swing.JTextField labaTF;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField pembeliTF;
    private javax.swing.JButton refreshBT;
    private javax.swing.JLabel tanggalLB;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
