/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koneksi_java;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class login2 extends javax.swing.JFrame {

    static String user1;
    static String pass1;
    /**
     * Creates new form login2
     */
    public login2() {
        initComponents();
        jLabel10.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginBT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        errorLB = new javax.swing.JLabel();
        penggunaCMB = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(240, 223, 154));
        jPanel2.setPreferredSize(new java.awt.Dimension(680, 560));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Berdikari-Book");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        loginBT.setText("Login");
        loginBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTActionPerformed(evt);
            }
        });
        jPanel2.add(loginBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 303, 86, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please insert your username and password!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        UsernameTF.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        UsernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTFActionPerformed(evt);
            }
        });
        jPanel2.add(UsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 149, -1));

        PasswordTF.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jPanel2.add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 149, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Version 1.0");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2leftarrow.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));

        errorLB.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        errorLB.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(errorLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 266, 18));

        penggunaCMB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- pilih --", "Admin", "Customer" }));
        penggunaCMB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        penggunaCMB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaCMBMouseClicked(evt);
            }
        });
        penggunaCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaCMBActionPerformed(evt);
            }
        });
        jPanel2.add(penggunaCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 146, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pengguna:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 120, 20));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Username or Email::");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("F:\\PICTURE\\Picture\\2041-3.jpg")); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-680, -340, 1480, 880));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTFActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        login lg=new login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void loginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTActionPerformed
        // TODO add your handling code here:
        String user=UsernameTF.getText();
        user1=UsernameTF.getText();
        pass1=PasswordTF.getText();
        String pass=PasswordTF.getText();
        String cekUser=null;
        String cekPass=null;
        String cekEmail=null;
        if (penggunaCMB.getSelectedItem().equals("Admin")){
              if (UsernameTF.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "User Name tidak boleh kosong");
                UsernameTF.requestFocus();
                 }
            else if (PasswordTF.getText().equals("")){
                  JOptionPane.showMessageDialog(rootPane, "Password tidak boleh kosong");
                  PasswordTF.requestFocus();
                   }
            else{
                try {
                    Connection koneksikan=koneksi.getkoneksikan();
                    Statement s=koneksikan.createStatement();
                    String sql="select *from admin where username='"+user+"'and password='"+pass+"'";
                    ResultSet r=s.executeQuery(sql);
                    while(r.next()){
                        cekUser=r.getString("username");
                        cekPass=r.getString("password");
                    }
                    r.close();
                    s.close();
                } catch (Exception e) {
                    System.out.println("Terjadi kesalahan");
                }
            if(cekUser==null&&cekPass==null){
                errorLB.setText("Username atau Password yang Anda masukkan salah");
            }else{
                String pesan="Login berhasil";
                JOptionPane.showMessageDialog(null, pesan, "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                homeAdmin hmA=new homeAdmin();
                hmA.setVisible(true);
            }}          
        }
        else if (penggunaCMB.getSelectedItem().equals("Customer")){
            jLabel10.setVisible(true);
            jLabel5.setVisible(false);
              if (UsernameTF.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "User Name tidak boleh kosong");
                UsernameTF.requestFocus();
                 }
            else if (PasswordTF.getText().equals("")){
                  JOptionPane.showMessageDialog(rootPane, "Password tidak boleh kosong");
                  PasswordTF.requestFocus();
                   }
            else{
                try {
                    Connection koneksikan=koneksi.getkoneksikan();
                    Statement s=koneksikan.createStatement();
                    String sql="select *from user where username='"+user+"'or email='"+user+"'and password='"+pass+"'";
                    ResultSet r=s.executeQuery(sql);
                    while(r.next()){
                        cekUser=r.getString("username");
                        cekEmail=r.getString("email");
                        cekPass=r.getString("password");
                    }
                    r.close();
                    s.close();
                } catch (Exception e) {
                    System.out.println("Terjadi kesalahan");
                }
            if(cekUser!=null||cekEmail!=null&&cekPass!=null){
                String pesan="Login berhasil";
                JOptionPane.showMessageDialog(null, pesan, "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                home hm=new home();
                hm.setVisible(true);
            }else{
                errorLB.setText("Username atau Password yang Anda masukkan salah");
            }}          
        }
    }//GEN-LAST:event_loginBTActionPerformed

    private void penggunaCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penggunaCMBActionPerformed

    private void penggunaCMBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaCMBMouseClicked
        // TODO add your handling code here:
        if (penggunaCMB.getSelectedItem().equals("Customer")){
            jLabel10.setVisible(true);
            jLabel5.setVisible(false);}
        else{
            jLabel10.setVisible(false);
            jLabel5.setVisible(true);
        }
    }//GEN-LAST:event_penggunaCMBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel errorLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBT;
    private javax.swing.JComboBox penggunaCMB;
    // End of variables declaration//GEN-END:variables
}
